// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartbeat.proto

package org.dreambot.analytics;

public final class HeartbeatProto {
  private HeartbeatProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_MouseData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_MouseData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_HeartBeat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_HeartBeat_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_HeartBeat_ExecuteCountsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_HeartBeat_ExecuteCountsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_HeartBeat_RegionDensitiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_HeartBeat_RegionDensitiesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017heartbeat.proto\022\010tutorial\"B\n\tMouseData" +
      "\022\014\n\004rows\030\001 \001(\r\022\014\n\004cols\030\002 \001(\r\022\031\n\rmouse_de" +
      "nsity\030\003 \003(\rB\002\020\001\"\350\010\n\tHeartBeat\022&\n\tmouse_p" +
      "os\030\001 \001(\0132\023.tutorial.MouseData\022)\n\014mouse_c" +
      "licks\030\' \001(\0132\023.tutorial.MouseData\022\033\n\023rela" +
      "tive_click_time\030- \003(\r\022>\n\016execute_counts\030" +
      "\002 \003(\0132&.tutorial.HeartBeat.ExecuteCounts" +
      "Entry\022B\n\020region_densities\030& \003(\0132(.tutori" +
      "al.HeartBeat.RegionDensitiesEntry\022\014\n\004tim" +
      "e\030\004 \001(\004\022\024\n\014account_hash\030\005 \001(\t\022\026\n\016dreambo" +
      "t_token\030\006 \001(\t\022\025\n\rdreambot_user\030\007 \001(\t\022\023\n\013" +
      "script_name\030\010 \001(\t\022\031\n\021heart_beat_length\030\t" +
      " \001(\r\022\025\n\rno_click_walk\030\n \001(\010\022\022\n\nmenu_mani" +
      "p\030\013 \001(\010\022\025\n\rtime_breaking\030\014 \001(\r\022\021\n\tis_mem" +
      "ber\030\r \001(\010\022\021\n\tis_covert\030\016 \001(\010\022\023\n\013mouse_sp" +
      "eed\030( \001(\r\022\025\n\ris_using_beta\030) \001(\010\022\025\n\riron" +
      "man_state\030+ \001(\r\022\024\n\014email_domain\030, \001(\t\022\016\n" +
      "\006wealth\030* \001(\r\022\016\n\006attack\030\003 \001(\r\022\020\n\010strengt" +
      "h\030\017 \001(\r\022\017\n\007defence\030\020 \001(\r\022\016\n\006ranged\030\021 \001(\r" +
      "\022\016\n\006prayer\030\022 \001(\r\022\r\n\005magic\030\023 \001(\r\022\021\n\trunec" +
      "raft\030\024 \001(\r\022\024\n\014construction\030\025 \001(\r\022\021\n\thitp" +
      "oints\030\026 \001(\r\022\017\n\007agility\030\027 \001(\r\022\020\n\010herblore" +
      "\030\030 \001(\r\022\020\n\010thieving\030\031 \001(\r\022\020\n\010crafting\030\032 \001" +
      "(\r\022\021\n\tfletching\030\033 \001(\r\022\016\n\006slayer\030\034 \001(\r\022\016\n" +
      "\006hunter\030\035 \001(\r\022\016\n\006mining\030\036 \001(\r\022\020\n\010smithin" +
      "g\030\037 \001(\r\022\017\n\007fishing\030  \001(\r\022\017\n\007cooking\030! \001(" +
      "\r\022\022\n\nfiremaking\030\" \001(\r\022\023\n\013woodcutting\030# \001" +
      "(\r\022\017\n\007farming\030$ \001(\r\022\017\n\007sailing\030% \001(\r\0324\n\022" +
      "ExecuteCountsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value" +
      "\030\002 \001(\r:\0028\001\0326\n\024RegionDensitiesEntry\022\013\n\003ke" +
      "y\030\001 \001(\r\022\r\n\005value\030\002 \001(\r:\0028\001B*\n\026org.dreamb" +
      "ot.analyticsB\016HeartbeatProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_MouseData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_MouseData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_MouseData_descriptor,
        new String[] { "Rows", "Cols", "MouseDensity", });
    internal_static_tutorial_HeartBeat_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_HeartBeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_HeartBeat_descriptor,
        new String[] { "MousePos", "MouseClicks", "RelativeClickTime", "ExecuteCounts", "RegionDensities", "Time", "AccountHash", "DreambotToken", "DreambotUser", "ScriptName", "HeartBeatLength", "NoClickWalk", "MenuManip", "TimeBreaking", "IsMember", "IsCovert", "MouseSpeed", "IsUsingBeta", "IronmanState", "EmailDomain", "Wealth", "Attack", "Strength", "Defence", "Ranged", "Prayer", "Magic", "Runecraft", "Construction", "Hitpoints", "Agility", "Herblore", "Thieving", "Crafting", "Fletching", "Slayer", "Hunter", "Mining", "Smithing", "Fishing", "Cooking", "Firemaking", "Woodcutting", "Farming", "Sailing", });
    internal_static_tutorial_HeartBeat_ExecuteCountsEntry_descriptor =
      internal_static_tutorial_HeartBeat_descriptor.getNestedTypes().get(0);
    internal_static_tutorial_HeartBeat_ExecuteCountsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_HeartBeat_ExecuteCountsEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_tutorial_HeartBeat_RegionDensitiesEntry_descriptor =
      internal_static_tutorial_HeartBeat_descriptor.getNestedTypes().get(1);
    internal_static_tutorial_HeartBeat_RegionDensitiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_HeartBeat_RegionDensitiesEntry_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
