// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartbeat.proto

package org.dreambot.analytics;

public interface HeartBeatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.HeartBeat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * antiban focused stuff
   * </pre>
   *
   * <code>.tutorial.MouseData mouse_pos = 1;</code>
   * @return Whether the mousePos field is set.
   */
  boolean hasMousePos();
  /**
   * <pre>
   * antiban focused stuff
   * </pre>
   *
   * <code>.tutorial.MouseData mouse_pos = 1;</code>
   * @return The mousePos.
   */
  MouseData getMousePos();
  /**
   * <pre>
   * antiban focused stuff
   * </pre>
   *
   * <code>.tutorial.MouseData mouse_pos = 1;</code>
   */
  MouseDataOrBuilder getMousePosOrBuilder();

  /**
   * <pre>
   * flat 2d array on where you clicked
   * </pre>
   *
   * <code>.tutorial.MouseData mouse_clicks = 39;</code>
   * @return Whether the mouseClicks field is set.
   */
  boolean hasMouseClicks();
  /**
   * <pre>
   * flat 2d array on where you clicked
   * </pre>
   *
   * <code>.tutorial.MouseData mouse_clicks = 39;</code>
   * @return The mouseClicks.
   */
  MouseData getMouseClicks();
  /**
   * <pre>
   * flat 2d array on where you clicked
   * </pre>
   *
   * <code>.tutorial.MouseData mouse_clicks = 39;</code>
   */
  MouseDataOrBuilder getMouseClicksOrBuilder();

  /**
   * <pre>
   * per mouse click recorded a relative click time, the time left on the 15 minute timer
   * mouse position is implicitly tracked 50ms, so by knowing time left you know the index of the preceding mouse pos
   * so this encodes mouse path
   * </pre>
   *
   * <code>repeated uint32 relative_click_time = 45;</code>
   * @return A list containing the relativeClickTime.
   */
  java.util.List<Integer> getRelativeClickTimeList();
  /**
   * <pre>
   * per mouse click recorded a relative click time, the time left on the 15 minute timer
   * mouse position is implicitly tracked 50ms, so by knowing time left you know the index of the preceding mouse pos
   * so this encodes mouse path
   * </pre>
   *
   * <code>repeated uint32 relative_click_time = 45;</code>
   * @return The count of relativeClickTime.
   */
  int getRelativeClickTimeCount();
  /**
   * <pre>
   * per mouse click recorded a relative click time, the time left on the 15 minute timer
   * mouse position is implicitly tracked 50ms, so by knowing time left you know the index of the preceding mouse pos
   * so this encodes mouse path
   * </pre>
   *
   * <code>repeated uint32 relative_click_time = 45;</code>
   * @param index The index of the element to return.
   * @return The relativeClickTime at the given index.
   */
  int getRelativeClickTime(int index);

  /**
   * <pre>
   * how many times the script executed, string is the decision path
   * </pre>
   *
   * <code>map&lt;string, uint32&gt; execute_counts = 2;</code>
   */
  int getExecuteCountsCount();
  /**
   * <pre>
   * how many times the script executed, string is the decision path
   * </pre>
   *
   * <code>map&lt;string, uint32&gt; execute_counts = 2;</code>
   */
  boolean containsExecuteCounts(
      String key);
  /**
   * Use {@link #getExecuteCountsMap()} instead.
   */
  @Deprecated
  java.util.Map<String, Integer>
  getExecuteCounts();
  /**
   * <pre>
   * how many times the script executed, string is the decision path
   * </pre>
   *
   * <code>map&lt;string, uint32&gt; execute_counts = 2;</code>
   */
  java.util.Map<String, Integer>
  getExecuteCountsMap();
  /**
   * <pre>
   * how many times the script executed, string is the decision path
   * </pre>
   *
   * <code>map&lt;string, uint32&gt; execute_counts = 2;</code>
   */

  int getExecuteCountsOrDefault(
      String key,
      int defaultValue);
  /**
   * <pre>
   * how many times the script executed, string is the decision path
   * </pre>
   *
   * <code>map&lt;string, uint32&gt; execute_counts = 2;</code>
   */

  int getExecuteCountsOrThrow(
      String key);

  /**
   * <pre>
   * great for bug detection
   * </pre>
   *
   * <code>map&lt;uint32, uint32&gt; region_densities = 38;</code>
   */
  int getRegionDensitiesCount();
  /**
   * <pre>
   * great for bug detection
   * </pre>
   *
   * <code>map&lt;uint32, uint32&gt; region_densities = 38;</code>
   */
  boolean containsRegionDensities(
      int key);
  /**
   * Use {@link #getRegionDensitiesMap()} instead.
   */
  @Deprecated
  java.util.Map<Integer, Integer>
  getRegionDensities();
  /**
   * <pre>
   * great for bug detection
   * </pre>
   *
   * <code>map&lt;uint32, uint32&gt; region_densities = 38;</code>
   */
  java.util.Map<Integer, Integer>
  getRegionDensitiesMap();
  /**
   * <pre>
   * great for bug detection
   * </pre>
   *
   * <code>map&lt;uint32, uint32&gt; region_densities = 38;</code>
   */

  int getRegionDensitiesOrDefault(
      int key,
      int defaultValue);
  /**
   * <pre>
   * great for bug detection
   * </pre>
   *
   * <code>map&lt;uint32, uint32&gt; region_densities = 38;</code>
   */

  int getRegionDensitiesOrThrow(
      int key);

  /**
   * <pre>
   * flags
   * </pre>
   *
   * <code>uint64 time = 4;</code>
   * @return The time.
   */
  long getTime();

  /**
   * <code>string account_hash = 5;</code>
   * @return The accountHash.
   */
  String getAccountHash();
  /**
   * <code>string account_hash = 5;</code>
   * @return The bytes for accountHash.
   */
  com.google.protobuf.ByteString
      getAccountHashBytes();

  /**
   * <code>string dreambot_token = 6;</code>
   * @return The dreambotToken.
   */
  String getDreambotToken();
  /**
   * <code>string dreambot_token = 6;</code>
   * @return The bytes for dreambotToken.
   */
  com.google.protobuf.ByteString
      getDreambotTokenBytes();

  /**
   * <code>string dreambot_user = 7;</code>
   * @return The dreambotUser.
   */
  String getDreambotUser();
  /**
   * <code>string dreambot_user = 7;</code>
   * @return The bytes for dreambotUser.
   */
  com.google.protobuf.ByteString
      getDreambotUserBytes();

  /**
   * <code>string script_name = 8;</code>
   * @return The scriptName.
   */
  String getScriptName();
  /**
   * <code>string script_name = 8;</code>
   * @return The bytes for scriptName.
   */
  com.google.protobuf.ByteString
      getScriptNameBytes();

  /**
   * <code>uint32 heart_beat_length = 9;</code>
   * @return The heartBeatLength.
   */
  int getHeartBeatLength();

  /**
   * <code>bool no_click_walk = 10;</code>
   * @return The noClickWalk.
   */
  boolean getNoClickWalk();

  /**
   * <code>bool menu_manip = 11;</code>
   * @return The menuManip.
   */
  boolean getMenuManip();

  /**
   * <code>uint32 time_breaking = 12;</code>
   * @return The timeBreaking.
   */
  int getTimeBreaking();

  /**
   * <code>bool is_member = 13;</code>
   * @return The isMember.
   */
  boolean getIsMember();

  /**
   * <code>bool is_covert = 14;</code>
   * @return The isCovert.
   */
  boolean getIsCovert();

  /**
   * <code>uint32 mouse_speed = 40;</code>
   * @return The mouseSpeed.
   */
  int getMouseSpeed();

  /**
   * <code>bool is_using_beta = 41;</code>
   * @return The isUsingBeta.
   */
  boolean getIsUsingBeta();

  /**
   * <pre>
   * state of varbit 1777
   * </pre>
   *
   * <code>uint32 ironman_state = 43;</code>
   * @return The ironmanState.
   */
  int getIronmanState();

  /**
   * <pre>
   * ive seen reports today of manual bans specifically on certain domains,
   * EF uses a set of domains, xitroo is a temp mail provider that got banned today
   * this just tracks the domain and thats why
   * </pre>
   *
   * <code>string email_domain = 44;</code>
   * @return The emailDomain.
   */
  String getEmailDomain();
  /**
   * <pre>
   * ive seen reports today of manual bans specifically on certain domains,
   * EF uses a set of domains, xitroo is a temp mail provider that got banned today
   * this just tracks the domain and thats why
   * </pre>
   *
   * <code>string email_domain = 44;</code>
   * @return The bytes for emailDomain.
   */
  com.google.protobuf.ByteString
      getEmailDomainBytes();

  /**
   * <code>uint32 wealth = 42;</code>
   * @return The wealth.
   */
  int getWealth();

  /**
   * <pre>
   * experience, for behavioural antiban
   * </pre>
   *
   * <code>uint32 attack = 3;</code>
   * @return The attack.
   */
  int getAttack();

  /**
   * <code>uint32 strength = 15;</code>
   * @return The strength.
   */
  int getStrength();

  /**
   * <code>uint32 defence = 16;</code>
   * @return The defence.
   */
  int getDefence();

  /**
   * <code>uint32 ranged = 17;</code>
   * @return The ranged.
   */
  int getRanged();

  /**
   * <code>uint32 prayer = 18;</code>
   * @return The prayer.
   */
  int getPrayer();

  /**
   * <code>uint32 magic = 19;</code>
   * @return The magic.
   */
  int getMagic();

  /**
   * <code>uint32 runecraft = 20;</code>
   * @return The runecraft.
   */
  int getRunecraft();

  /**
   * <code>uint32 construction = 21;</code>
   * @return The construction.
   */
  int getConstruction();

  /**
   * <code>uint32 hitpoints = 22;</code>
   * @return The hitpoints.
   */
  int getHitpoints();

  /**
   * <code>uint32 agility = 23;</code>
   * @return The agility.
   */
  int getAgility();

  /**
   * <code>uint32 herblore = 24;</code>
   * @return The herblore.
   */
  int getHerblore();

  /**
   * <code>uint32 thieving = 25;</code>
   * @return The thieving.
   */
  int getThieving();

  /**
   * <code>uint32 crafting = 26;</code>
   * @return The crafting.
   */
  int getCrafting();

  /**
   * <code>uint32 fletching = 27;</code>
   * @return The fletching.
   */
  int getFletching();

  /**
   * <code>uint32 slayer = 28;</code>
   * @return The slayer.
   */
  int getSlayer();

  /**
   * <code>uint32 hunter = 29;</code>
   * @return The hunter.
   */
  int getHunter();

  /**
   * <code>uint32 mining = 30;</code>
   * @return The mining.
   */
  int getMining();

  /**
   * <code>uint32 smithing = 31;</code>
   * @return The smithing.
   */
  int getSmithing();

  /**
   * <code>uint32 fishing = 32;</code>
   * @return The fishing.
   */
  int getFishing();

  /**
   * <code>uint32 cooking = 33;</code>
   * @return The cooking.
   */
  int getCooking();

  /**
   * <code>uint32 firemaking = 34;</code>
   * @return The firemaking.
   */
  int getFiremaking();

  /**
   * <code>uint32 woodcutting = 35;</code>
   * @return The woodcutting.
   */
  int getWoodcutting();

  /**
   * <code>uint32 farming = 36;</code>
   * @return The farming.
   */
  int getFarming();

  /**
   * <code>uint32 sailing = 37;</code>
   * @return The sailing.
   */
  int getSailing();
}
