// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartbeat.proto

package org.dreambot.analytics;

/**
 * <pre>
 * matrix of time(in 50ms intervals) spent in a percentile box. flattened
 * </pre>
 *
 * Protobuf type {@code tutorial.MouseData}
 */
public final class MouseData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tutorial.MouseData)
    MouseDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MouseData.newBuilder() to construct.
  private MouseData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MouseData() {
    mouseDensity_ = emptyIntList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new MouseData();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MouseData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            rows_ = input.readUInt32();
            break;
          }
          case 16: {

            cols_ = input.readUInt32();
            break;
          }
          case 24: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              mouseDensity_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            mouseDensity_.addInt(input.readUInt32());
            break;
          }
          case 26: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              mouseDensity_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              mouseDensity_.addInt(input.readUInt32());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        mouseDensity_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return HeartbeatProto.internal_static_tutorial_MouseData_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return HeartbeatProto.internal_static_tutorial_MouseData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            MouseData.class, Builder.class);
  }

  public static final int ROWS_FIELD_NUMBER = 1;
  private int rows_;
  /**
   * <code>uint32 rows = 1;</code>
   * @return The rows.
   */
  @Override
  public int getRows() {
    return rows_;
  }

  public static final int COLS_FIELD_NUMBER = 2;
  private int cols_;
  /**
   * <code>uint32 cols = 2;</code>
   * @return The cols.
   */
  @Override
  public int getCols() {
    return cols_;
  }

  public static final int MOUSE_DENSITY_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.IntList mouseDensity_;
  /**
   * <code>repeated uint32 mouse_density = 3 [packed = true];</code>
   * @return A list containing the mouseDensity.
   */
  @Override
  public java.util.List<Integer>
      getMouseDensityList() {
    return mouseDensity_;
  }
  /**
   * <code>repeated uint32 mouse_density = 3 [packed = true];</code>
   * @return The count of mouseDensity.
   */
  public int getMouseDensityCount() {
    return mouseDensity_.size();
  }
  /**
   * <code>repeated uint32 mouse_density = 3 [packed = true];</code>
   * @param index The index of the element to return.
   * @return The mouseDensity at the given index.
   */
  public int getMouseDensity(int index) {
    return mouseDensity_.getInt(index);
  }
  private int mouseDensityMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (rows_ != 0) {
      output.writeUInt32(1, rows_);
    }
    if (cols_ != 0) {
      output.writeUInt32(2, cols_);
    }
    if (getMouseDensityList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(mouseDensityMemoizedSerializedSize);
    }
    for (int i = 0; i < mouseDensity_.size(); i++) {
      output.writeUInt32NoTag(mouseDensity_.getInt(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (rows_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, rows_);
    }
    if (cols_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, cols_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < mouseDensity_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(mouseDensity_.getInt(i));
      }
      size += dataSize;
      if (!getMouseDensityList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      mouseDensityMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof MouseData)) {
      return super.equals(obj);
    }
    MouseData other = (MouseData) obj;

    if (getRows()
        != other.getRows()) return false;
    if (getCols()
        != other.getCols()) return false;
    if (!getMouseDensityList()
        .equals(other.getMouseDensityList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ROWS_FIELD_NUMBER;
    hash = (53 * hash) + getRows();
    hash = (37 * hash) + COLS_FIELD_NUMBER;
    hash = (53 * hash) + getCols();
    if (getMouseDensityCount() > 0) {
      hash = (37 * hash) + MOUSE_DENSITY_FIELD_NUMBER;
      hash = (53 * hash) + getMouseDensityList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static MouseData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MouseData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MouseData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MouseData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MouseData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MouseData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MouseData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MouseData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static MouseData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static MouseData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static MouseData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MouseData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(MouseData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * matrix of time(in 50ms intervals) spent in a percentile box. flattened
   * </pre>
   *
   * Protobuf type {@code tutorial.MouseData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tutorial.MouseData)
      MouseDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HeartbeatProto.internal_static_tutorial_MouseData_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HeartbeatProto.internal_static_tutorial_MouseData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MouseData.class, Builder.class);
    }

    // Construct using org.dreambot.analytics.MouseData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      rows_ = 0;

      cols_ = 0;

      mouseDensity_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return HeartbeatProto.internal_static_tutorial_MouseData_descriptor;
    }

    @Override
    public MouseData getDefaultInstanceForType() {
      return MouseData.getDefaultInstance();
    }

    @Override
    public MouseData build() {
      MouseData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public MouseData buildPartial() {
      MouseData result = new MouseData(this);
      int from_bitField0_ = bitField0_;
      result.rows_ = rows_;
      result.cols_ = cols_;
      if (((bitField0_ & 0x00000001) != 0)) {
        mouseDensity_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.mouseDensity_ = mouseDensity_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof MouseData) {
        return mergeFrom((MouseData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(MouseData other) {
      if (other == MouseData.getDefaultInstance()) return this;
      if (other.getRows() != 0) {
        setRows(other.getRows());
      }
      if (other.getCols() != 0) {
        setCols(other.getCols());
      }
      if (!other.mouseDensity_.isEmpty()) {
        if (mouseDensity_.isEmpty()) {
          mouseDensity_ = other.mouseDensity_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureMouseDensityIsMutable();
          mouseDensity_.addAll(other.mouseDensity_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      MouseData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (MouseData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int rows_ ;
    /**
     * <code>uint32 rows = 1;</code>
     * @return The rows.
     */
    @Override
    public int getRows() {
      return rows_;
    }
    /**
     * <code>uint32 rows = 1;</code>
     * @param value The rows to set.
     * @return This builder for chaining.
     */
    public Builder setRows(int value) {
      
      rows_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 rows = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRows() {
      
      rows_ = 0;
      onChanged();
      return this;
    }

    private int cols_ ;
    /**
     * <code>uint32 cols = 2;</code>
     * @return The cols.
     */
    @Override
    public int getCols() {
      return cols_;
    }
    /**
     * <code>uint32 cols = 2;</code>
     * @param value The cols to set.
     * @return This builder for chaining.
     */
    public Builder setCols(int value) {
      
      cols_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 cols = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCols() {
      
      cols_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList mouseDensity_ = emptyIntList();
    private void ensureMouseDensityIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        mouseDensity_ = mutableCopy(mouseDensity_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated uint32 mouse_density = 3 [packed = true];</code>
     * @return A list containing the mouseDensity.
     */
    public java.util.List<Integer>
        getMouseDensityList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(mouseDensity_) : mouseDensity_;
    }
    /**
     * <code>repeated uint32 mouse_density = 3 [packed = true];</code>
     * @return The count of mouseDensity.
     */
    public int getMouseDensityCount() {
      return mouseDensity_.size();
    }
    /**
     * <code>repeated uint32 mouse_density = 3 [packed = true];</code>
     * @param index The index of the element to return.
     * @return The mouseDensity at the given index.
     */
    public int getMouseDensity(int index) {
      return mouseDensity_.getInt(index);
    }
    /**
     * <code>repeated uint32 mouse_density = 3 [packed = true];</code>
     * @param index The index to set the value at.
     * @param value The mouseDensity to set.
     * @return This builder for chaining.
     */
    public Builder setMouseDensity(
        int index, int value) {
      ensureMouseDensityIsMutable();
      mouseDensity_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated uint32 mouse_density = 3 [packed = true];</code>
     * @param value The mouseDensity to add.
     * @return This builder for chaining.
     */
    public Builder addMouseDensity(int value) {
      ensureMouseDensityIsMutable();
      mouseDensity_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated uint32 mouse_density = 3 [packed = true];</code>
     * @param values The mouseDensity to add.
     * @return This builder for chaining.
     */
    public Builder addAllMouseDensity(
        Iterable<? extends Integer> values) {
      ensureMouseDensityIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, mouseDensity_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated uint32 mouse_density = 3 [packed = true];</code>
     * @return This builder for chaining.
     */
    public Builder clearMouseDensity() {
      mouseDensity_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tutorial.MouseData)
  }

  // @@protoc_insertion_point(class_scope:tutorial.MouseData)
  private static final MouseData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new MouseData();
  }

  public static MouseData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MouseData>
      PARSER = new com.google.protobuf.AbstractParser<MouseData>() {
    @Override
    public MouseData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MouseData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MouseData> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<MouseData> getParserForType() {
    return PARSER;
  }

  @Override
  public MouseData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

