package org.dreambot.behaviour.smithing;

import org.dreambot.loadouts.data.ItemID;

/**
 * Items you smith at an anvil
 */
public enum SmithingItem {
    // bronze
    BRONZE_DAGGER(ItemID.BRONZE_DAGGER, SmithingBar.BRONZE, 1),
    BRONZE_AXE(ItemID.BRONZE_AXE, SmithingBar.BRONZE, 1),
    BRONZE_MACE(ItemID.BRONZE_MACE, SmithingBar.BRONZE, 1),
    BRONZE_MED_HELM(ItemID.BRONZE_MED_HELM, SmithingBar.BRONZE, 1),
    BRONZE_SWORD(ItemID.BRONZE_SWORD, SmithingBar.BRONZE, 1),
    BRONZE_SCIM(ItemID.BRONZE_SCIMITAR, SmithingBar.BRONZE, 2),
    BRONZE_LONGSWORD(ItemID.BRONZE_LONGSWORD, SmithingBar.BRONZE, 2),
    BRONZE_FULL_HELM(ItemID.BRONZE_FULL_HELM, SmithingBar.BRONZE, 2),
    BRONZE_SQ_SHIELD(ItemID.BRONZE_SQ_SHIELD, SmithingBar.BRONZE, 2),
    BRONZE_WARHAMMER(ItemID.BRONZE_WARHAMMER, SmithingBar.BRONZE, 3),
    BRONZE_BATTLEAXE(ItemID.BRONZE_BATTLEAXE, SmithingBar.BRONZE, 3),
    BRONZE_CHAINBODY(ItemID.BRONZE_CHAINBODY, SmithingBar.BRONZE, 3),
    BRONZE_KITESHIELD(ItemID.BRONZE_KITESHIELD, SmithingBar.BRONZE, 3),
    BRONZE_2H(ItemID.BRONZE_2H_SWORD, SmithingBar.BRONZE, 3),
    BRONZE_PLATELEGS(ItemID.BRONZE_PLATELEGS, SmithingBar.BRONZE, 3),
    BRONZE_PLATESKIRT(ItemID.BRONZE_PLATESKIRT, SmithingBar.BRONZE, 3),
    BRONZE_PLATEBODY(ItemID.BRONZE_PLATEBODY, SmithingBar.BRONZE, 5),


    // iron
    IRON_DAGGER(ItemID.IRON_DAGGER, SmithingBar.IRON, 1),
    IRON_AXE(ItemID.IRON_AXE, SmithingBar.IRON, 1),
    IRON_MACE(ItemID.IRON_MACE, SmithingBar.IRON, 1),
    IRON_MED_HELM(ItemID.IRON_MED_HELM, SmithingBar.IRON, 1),
    IRON_SWORD(ItemID.IRON_SWORD, SmithingBar.IRON, 1),
    IRON_SCIM(ItemID.IRON_SCIMITAR, SmithingBar.IRON, 2),
    IRON_LONGSWORD(ItemID.IRON_LONGSWORD, SmithingBar.IRON, 2),
    IRON_FULL_HELM(ItemID.IRON_FULL_HELM, SmithingBar.IRON, 2),
    IRON_SQ_SHIELD(ItemID.IRON_SQ_SHIELD, SmithingBar.IRON, 2),
    IRON_WARHAMMER(ItemID.IRON_WARHAMMER, SmithingBar.IRON, 3),
    IRON_BATTLEAXE(ItemID.IRON_BATTLEAXE, SmithingBar.IRON, 3),
    IRON_CHAINBODY(ItemID.IRON_CHAINBODY, SmithingBar.IRON, 3),
    IRON_KITESHIELD(ItemID.IRON_KITESHIELD, SmithingBar.IRON, 3),
    IRON_2H(ItemID.IRON_2H_SWORD, SmithingBar.IRON, 3),
    IRON_PLATELEGS(ItemID.IRON_PLATELEGS, SmithingBar.IRON, 3),
    IRON_PLATESKIRT(ItemID.IRON_PLATESKIRT, SmithingBar.IRON, 3),
    IRON_PLATEBODY(ItemID.IRON_PLATEBODY, SmithingBar.IRON, 5),

    // steel
    STEEL_DAGGER(ItemID.STEEL_DAGGER, SmithingBar.STEEL, 1),
    STEEL_AXE(ItemID.STEEL_AXE, SmithingBar.STEEL, 1),
    STEEL_MACE(ItemID.STEEL_MACE, SmithingBar.STEEL, 1),
    STEEL_MED_HELM(ItemID.STEEL_MED_HELM, SmithingBar.STEEL, 1),
    STEEL_SWORD(ItemID.STEEL_SWORD, SmithingBar.STEEL, 1),
    STEEL_SCIM(ItemID.STEEL_SCIMITAR, SmithingBar.STEEL, 2),
    STEEL_LONGSWORD(ItemID.STEEL_LONGSWORD, SmithingBar.STEEL, 2),
    STEEL_FULL_HELM(ItemID.STEEL_FULL_HELM, SmithingBar.STEEL, 2),
    STEEL_SQ_SHIELD(ItemID.STEEL_SQ_SHIELD, SmithingBar.STEEL, 2),
    STEEL_WARHAMMER(ItemID.STEEL_WARHAMMER, SmithingBar.STEEL, 3),
    STEEL_BATTLEAXE(ItemID.STEEL_BATTLEAXE, SmithingBar.STEEL, 3),
    STEEL_CHAINBODY(ItemID.STEEL_CHAINBODY, SmithingBar.STEEL, 3),
    STEEL_KITESHIELD(ItemID.STEEL_KITESHIELD, SmithingBar.STEEL, 3),
    STEEL_2H(ItemID.STEEL_2H_SWORD, SmithingBar.STEEL, 3),
    STEEL_PLATELEGS(ItemID.STEEL_PLATELEGS, SmithingBar.STEEL, 3),
    STEEL_PLATESKIRT(ItemID.STEEL_PLATESKIRT, SmithingBar.STEEL, 3),
    STEEL_PLATEBODY(ItemID.STEEL_PLATEBODY, SmithingBar.STEEL, 5),

    // gold is crafting items

    // mithril
    MITHRIL_DAGGER(ItemID.MITHRIL_DAGGER, SmithingBar.MITHRIL, 1),
    MITHRIL_AXE(ItemID.MITHRIL_AXE, SmithingBar.MITHRIL, 1),
    MITHRIL_MACE(ItemID.MITHRIL_MACE, SmithingBar.MITHRIL, 1),
    MITHRIL_MED_HELM(ItemID.MITHRIL_MED_HELM, SmithingBar.MITHRIL, 1),
    MITHRIL_SWORD(ItemID.MITHRIL_SWORD, SmithingBar.MITHRIL, 1),
    MITHRIL_SCIM(ItemID.MITHRIL_SCIMITAR, SmithingBar.MITHRIL, 2),
    MITHRIL_LONGSWORD(ItemID.MITHRIL_LONGSWORD, SmithingBar.MITHRIL, 2),
    MITHRIL_FULL_HELM(ItemID.MITHRIL_FULL_HELM, SmithingBar.MITHRIL, 2),
    MITHRIL_SQ_SHIELD(ItemID.MITHRIL_SQ_SHIELD, SmithingBar.MITHRIL, 2),
    MITHRIL_WARHAMMER(ItemID.MITHRIL_WARHAMMER, SmithingBar.MITHRIL, 3),
    MITHRIL_BATTLEAXE(ItemID.MITHRIL_BATTLEAXE, SmithingBar.MITHRIL, 3),
    MITHRIL_CHAINBODY(ItemID.MITHRIL_CHAINBODY, SmithingBar.MITHRIL, 3),
    MITHRIL_KITESHIELD(ItemID.MITHRIL_KITESHIELD, SmithingBar.MITHRIL, 3),
    MITHRIL_2H(ItemID.MITHRIL_2H_SWORD, SmithingBar.MITHRIL, 3),
    MITHRIL_PLATELEGS(ItemID.MITHRIL_PLATELEGS, SmithingBar.MITHRIL, 3),
    MITHRIL_PLATESKIRT(ItemID.MITHRIL_PLATESKIRT, SmithingBar.MITHRIL, 3),
    MITHRIL_PLATEBODY(ItemID.MITHRIL_PLATEBODY, SmithingBar.MITHRIL, 5),

    // adamant
    ADAMANT_DAGGER(ItemID.ADAMANT_DAGGER, SmithingBar.ADAMANT, 1),
    ADAMANT_AXE(ItemID.ADAMANT_AXE, SmithingBar.ADAMANT, 1),
    ADAMANT_MACE(ItemID.ADAMANT_MACE, SmithingBar.ADAMANT, 1),
    ADAMANT_MED_HELM(ItemID.ADAMANT_MED_HELM, SmithingBar.ADAMANT, 1),
    ADAMANT_SWORD(ItemID.ADAMANT_SWORD, SmithingBar.ADAMANT, 1),
    ADAMANT_SCIM(ItemID.ADAMANT_SCIMITAR, SmithingBar.ADAMANT, 2),
    ADAMANT_LONGSWORD(ItemID.ADAMANT_LONGSWORD, SmithingBar.ADAMANT, 2),
    ADAMANT_FULL_HELM(ItemID.ADAMANT_FULL_HELM, SmithingBar.ADAMANT, 2),
    ADAMANT_SQ_SHIELD(ItemID.ADAMANT_SQ_SHIELD, SmithingBar.ADAMANT, 2),
    ADAMANT_WARHAMMER(ItemID.ADAMANT_WARHAMMER, SmithingBar.ADAMANT, 3),
    ADAMANT_BATTLEAXE(ItemID.ADAMANT_BATTLEAXE, SmithingBar.ADAMANT, 3),
    ADAMANT_CHAINBODY(ItemID.ADAMANT_CHAINBODY, SmithingBar.ADAMANT, 3),
    ADAMANT_KITESHIELD(ItemID.ADAMANT_KITESHIELD, SmithingBar.ADAMANT, 3),
    ADAMANT_2H(ItemID.ADAMANT_2H_SWORD, SmithingBar.ADAMANT, 3),
    ADAMANT_PLATELEGS(ItemID.ADAMANT_PLATELEGS, SmithingBar.ADAMANT, 3),
    ADAMANT_PLATESKIRT(ItemID.ADAMANT_PLATESKIRT, SmithingBar.ADAMANT, 3),
    ADAMANT_PLATEBODY(ItemID.ADAMANT_PLATEBODY, SmithingBar.ADAMANT, 5),

    // rune
    RUNE_DAGGER(ItemID.RUNE_DAGGER, SmithingBar.RUNE, 1),
    RUNE_AXE(ItemID.RUNE_AXE, SmithingBar.RUNE, 1),
    RUNE_MACE(ItemID.RUNE_MACE, SmithingBar.RUNE, 1),
    RUNE_MED_HELM(ItemID.RUNE_MED_HELM, SmithingBar.RUNE, 1),
    RUNE_SWORD(ItemID.RUNE_SWORD, SmithingBar.RUNE, 1),
    RUNE_SCIM(ItemID.RUNE_SCIMITAR, SmithingBar.RUNE, 2),
    RUNE_LONGSWORD(ItemID.RUNE_LONGSWORD, SmithingBar.RUNE, 2),
    RUNE_FULL_HELM(ItemID.RUNE_FULL_HELM, SmithingBar.RUNE, 2),
    RUNE_SQ_SHIELD(ItemID.RUNE_SQ_SHIELD, SmithingBar.RUNE, 2),
    RUNE_WARHAMMER(ItemID.RUNE_WARHAMMER, SmithingBar.RUNE, 3),
    RUNE_BATTLEAXE(ItemID.RUNE_BATTLEAXE, SmithingBar.RUNE, 3),
    RUNE_CHAINBODY(ItemID.RUNE_CHAINBODY, SmithingBar.RUNE, 3),
    RUNE_KITESHIELD(ItemID.RUNE_KITESHIELD, SmithingBar.RUNE, 3),
    RUNE_2H(ItemID.RUNE_2H_SWORD, SmithingBar.RUNE, 3),
    RUNE_PLATELEGS(ItemID.RUNE_PLATELEGS, SmithingBar.RUNE, 3),
    RUNE_PLATESKIRT(ItemID.RUNE_PLATESKIRT, SmithingBar.RUNE, 3),
    RUNE_PLATEBODY(ItemID.RUNE_PLATEBODY, SmithingBar.RUNE, 5),

    ;

    final int itemId;
    final SmithingBar bar;
    final int barCount;

    SmithingItem(int itemId, SmithingBar bar, int barCount) {
        this.itemId = itemId;
        this.bar = bar;
        this.barCount = barCount;
    }
}
