// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartbeat.proto

package org.dreambot.analytics;

public interface MouseDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.MouseData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 rows = 1;</code>
   * @return The rows.
   */
  int getRows();

  /**
   * <code>uint32 cols = 2;</code>
   * @return The cols.
   */
  int getCols();

  /**
   * <code>repeated uint32 mouse_density = 3 [packed = true];</code>
   * @return A list containing the mouseDensity.
   */
  java.util.List<java.lang.Integer> getMouseDensityList();
  /**
   * <code>repeated uint32 mouse_density = 3 [packed = true];</code>
   * @return The count of mouseDensity.
   */
  int getMouseDensityCount();
  /**
   * <code>repeated uint32 mouse_density = 3 [packed = true];</code>
   * @param index The index of the element to return.
   * @return The mouseDensity at the given index.
   */
  int getMouseDensity(int index);
}
